### ISSUE TITLE
Wrong homepage in dist.ini and debian packaging

### ISSUE THREAD

**Issue by xtaran** [dod38fr/config-model-tk-ui#1]
Hi Dominique,

another thing [DUCK](http://duck.debian.net/) found:

```
/home/abe/pkg-perl/git/packages/libconfig-model-tkui-perl
E: debian/control: Homepage: http://config-model.wiki.sourceforge.net: ERROR (Certainty:certain)
   Curl:0 HTTP:404 No error
```

https://github.com/dod38fr/config-model-tk-ui/blob/master/dist.ini says:

```
homepage = https://github.com/dod38fr/config-model-tkui/wiki
```

But that gives a 404, too.

I noticed the `tkui` vs `tk-ui`, but https://github.com/dod38fr/config-model-tk-ui/wiki doesn't exist either.

Would you be so kind to have a look at these things, too?

TIA!

**Comment by dod38fr** [comment]
Fixed in 456a1da35b6ebeea55a0b56135711a53d2bb672c

Thanks for the heads-up
