### ISSUE TITLE
Adjustable font size?

### ISSUE THREAD

**Issue by jvalleroy** [dod38fr/config-model-tk-ui#12]
When I run "cme edit dpkg" or similar, the Tk GUI editor font is very tiny on my 3200x1800 laptop screen. Is there any way to adjust this?

**Comment by dod38fr** [comment]
There may be a way with xrdb... But I don't know how...

That said, that way would not be user friendly. I'll modify Config::Model::TkUI to provide a menu to change the font. This will be based on [Tk::FontDialog](http://search.cpan.org/perldoc?Tk%3A%3AFontDialog) which is not (yet) packaged for Debian,

All the best

**Comment by dod38fr** [comment]
A possible workaround is to launch `cme` with option `-font`. I.e something like:
```
cme edit ssh -font "Arial 14"
```

**Comment by jvalleroy** [comment]
@dod38fr I can confirm that the workaround fixes the issue for me.

**Comment by dod38fr** [comment]
Next version will feature a new "Options->Font" menu to select the font and size used by "cme edit"

**Comment by dod38fr** [comment]
done with v1.364
